In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy


In [8]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 9522381209411521951
xla_global_id: -1
]


In [3]:
import tensorflow as tf
physical_devices = tf.config.experimental.list_physical_devices("GPU")
print(len(physical_devices))

0


In [4]:
from tensorflow import __version__
__version__

'2.7.0'

In [20]:
model = Sequential([
        Dense(units=10, input_shape=(6,), activation="relu", bias_initializer="RandomNormal" ), #first hidden layer
        Dense(units=5, activation="softmax", bias_initializer="RandomNormal"), #output
        
        ])

In [21]:
model.weights

[<tf.Variable 'dense_6/kernel:0' shape=(6, 10) dtype=float32, numpy=
 array([[-0.58854395,  0.08984739, -0.11432636, -0.07240129, -0.25191474,
          0.1344549 , -0.0653649 ,  0.44237608,  0.46490055,  0.5698946 ],
        [-0.15818402,  0.54284376,  0.4756326 ,  0.18164694,  0.46154898,
          0.41615444,  0.09388214, -0.22688654, -0.49517295,  0.24244905],
        [-0.33842063,  0.39629155, -0.2547073 ,  0.30843627,  0.4694875 ,
          0.28994697,  0.55356365, -0.2572594 , -0.58057576, -0.2727837 ],
        [-0.18887329, -0.24439657, -0.00136966,  0.23863769, -0.05615342,
         -0.02310127, -0.42701358, -0.43081748, -0.51982653,  0.08934456],
        [-0.47476566, -0.36289006, -0.05819058,  0.46221298, -0.35619622,
          0.3018598 , -0.10103106,  0.5361008 , -0.53260136,  0.4518121 ],
        [-0.21089622, -0.51679003, -0.06850469, -0.29835224, -0.32450277,
         -0.27552485, -0.32206777, -0.28082016, -0.0852533 ,  0.58349055]],
       dtype=float32)>,
 <tf.Variabl

In [19]:
wg1 = model.weights
wg1

[<tf.Variable 'dense_4/kernel:0' shape=(6, 10) dtype=float32, numpy=
 array([[ 0.37207723, -0.16884413,  0.23532641,  0.32854205,  0.08007991,
          0.30718923, -0.5644662 , -0.18320742,  0.31231815, -0.26835898],
        [ 0.3560514 ,  0.3348348 , -0.16005751, -0.07671225, -0.4895601 ,
          0.09265614,  0.04700732, -0.42714965, -0.07550806, -0.20731992],
        [ 0.0627563 , -0.26939952, -0.26847315,  0.25917757,  0.28679496,
          0.5252779 , -0.20714006,  0.2211811 ,  0.44929343,  0.17054725],
        [ 0.04944485, -0.5285717 ,  0.1045084 ,  0.4341126 , -0.28222308,
          0.54749936,  0.5752359 , -0.01062667,  0.27225018, -0.30018952],
        [-0.5260821 , -0.44564563,  0.02359229, -0.2741034 ,  0.30011725,
         -0.4426599 , -0.203834  ,  0.03242445, -0.2376782 , -0.31614175],
        [-0.43519223,  0.1373412 , -0.56972647, -0.38865882, -0.53641504,
         -0.25752863,  0.39445215,  0.55147606,  0.2754457 , -0.3341676 ]],
       dtype=float32)>,
 <tf.Variabl

In [23]:
model = Sequential([
        Dense(units=10, input_shape=(6,), activation="relu", bias_initializer="RandomNormal" ), #first hidden layer
        Dense(units=5, activation="softmax", bias_initializer="RandomNormal"), #output
        
        ])
model..set_weights(wg1)
model.weights

AttributeError: 'NoneType' object has no attribute 'weights'

In [17]:
troll_list = np.array([1,2,3,4,5,6])
troll_list = troll_list.reshape(1,6)
troll_list

array([[1, 2, 3, 4, 5, 6]])

In [19]:
import numpy as np
prediction = model.predict(troll_list)

In [23]:
prediction.argmax()

4

In [189]:
model.weights

[<tf.Variable 'dense_10/kernel:0' shape=(6, 10) dtype=float32, numpy=
 array([[ 0.3303269 ,  0.49272436,  0.11734623,  0.43968588, -0.20411491,
         -0.32208735, -0.4486944 ,  0.00063819,  0.1566853 , -0.5047921 ],
        [ 0.32089478, -0.5409337 ,  0.5325498 ,  0.09458864,  0.37957698,
         -0.44595104,  0.44402224,  0.01434606, -0.17901427,  0.24032068],
        [-0.21201473,  0.5849356 , -0.07611585, -0.24667725, -0.6061711 ,
          0.08153188,  0.299887  , -0.14579758,  0.53336555,  0.1737439 ],
        [ 0.06815881,  0.17767167,  0.29013753, -0.33828366,  0.3716554 ,
          0.03316104, -0.50647897,  0.45457035,  0.20950514,  0.20572513],
        [ 0.15399218,  0.29901803, -0.13227922,  0.39984375, -0.17038855,
         -0.05421615,  0.047795  , -0.14655519, -0.00803047, -0.53433394],
        [-0.269176  ,  0.5681495 , -0.20721158, -0.34706563,  0.48666626,
          0.14048415, -0.57109785, -0.38443387, -0.3920675 , -0.40147522]],
       dtype=float32)>,
 <tf.Variab

In [190]:
model.set_weights(weights1)

In [191]:
model.weights

[<tf.Variable 'dense_10/kernel:0' shape=(6, 10) dtype=float32, numpy=
 array([[-0.20550191,  0.43632013, -0.1247063 ,  0.36417955, -0.05435193,
          0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671],
        [-0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
          0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ],
        [-0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
         -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734],
        [ 0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
         -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ],
        [ 0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
         -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106],
        [ 0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
          0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ]],
       dtype=float32)>,
 <tf.Variab

In [192]:
weights1 = model.weights

In [193]:
weights1

[<tf.Variable 'dense_10/kernel:0' shape=(6, 10) dtype=float32, numpy=
 array([[-0.20550191,  0.43632013, -0.1247063 ,  0.36417955, -0.05435193,
          0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671],
        [-0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
          0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ],
        [-0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
         -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734],
        [ 0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
         -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ],
        [ 0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
         -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106],
        [ 0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
          0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ]],
       dtype=float32)>,
 <tf.Variab

In [194]:
old_shape = weights1[0].numpy().shape
weights1[0].numpy().flatten().reshape(old_shape)

array([[-0.20550191,  0.43632013, -0.1247063 ,  0.36417955, -0.05435193,
         0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671],
       [-0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
         0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ],
       [-0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
        -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734],
       [ 0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
        -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ],
       [ 0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
        -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106],
       [ 0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
         0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ]],
      dtype=float32)

In [195]:
old_shapes = []
for x in range(0,len(weights1)):
    old_shapes.append(weights1[x].numpy().shape)
old_shapes

[(6, 10), (10,), (10, 5), (5,)]

In [196]:
weights1[2].numpy().flatten()

array([-0.15617278, -0.45003837,  0.41482037,  0.35947788, -0.22490022,
        0.41105002, -0.27210248,  0.24810135,  0.03037363, -0.580385  ,
        0.38000232, -0.01188642,  0.38543016,  0.01838088,  0.533446  ,
       -0.20550299,  0.32569462,  0.5760369 , -0.11196172, -0.09118807,
        0.19937205,  0.36792284,  0.336533  , -0.34450963,  0.17339534,
       -0.55078   , -0.44134128, -0.22120059,  0.2772144 ,  0.23731697,
       -0.43873897, -0.25424346, -0.6197645 , -0.5574616 ,  0.04133689,
       -0.3793134 ,  0.2575391 ,  0.33048624, -0.20838049,  0.41090935,
       -0.28052872, -0.47728187,  0.447558  , -0.52149206, -0.03864241,
       -0.07749552,  0.06601971,  0.35028815,  0.09899777,  0.07422912],
      dtype=float32)

In [197]:
import numpy as np
flat_list = [weights1[0].numpy().flatten(),  weights1[1].numpy().flatten(), weights1[2].numpy().flatten(), weights1[3].numpy().flatten()]
#weights_combined = np.array([])
weights_combined = np.concatenate(( flat_list))
weights_combined[1] = 1

In [198]:
weights_combined

array([-0.20550191,  1.        , -0.1247063 ,  0.36417955, -0.05435193,
        0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671,
       -0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
        0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ,
       -0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
       -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734,
        0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
       -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ,
        0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
       -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106,
        0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
        0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ,
        0.0667546 , -0.03175627, -0.01404304,  0.04249647,  0.05407047,
        0.00670695,  0.03647355,  0.03131673, -0.00343134, -0.01

In [171]:
weights1[0].numpy().flatten()

array([-0.20550191,  0.43632013, -0.1247063 ,  0.36417955, -0.05435193,
        0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671,
       -0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
        0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ,
       -0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
       -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734,
        0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
       -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ,
        0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
       -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106,
        0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
        0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ],
      dtype=float32)

In [201]:
new_weights1 = weights_combined[:len(weights1[0].numpy().flatten())].reshape(old_shapes[0])
weights_combined = np.delete(weights_combined,np.s_[:len(weights1[0].numpy().flatten())])
len(weights_combined)

65

In [202]:
new_weights2 = weights_combined[:len(weights1[1].numpy().flatten())].reshape(old_shapes[1])
weights_combined = np.delete(weights_combined,np.s_[:len(weights1[1].numpy().flatten())])
len(weights_combined)

55

In [203]:
new_weights3 = weights_combined[:len(weights1[2].numpy().flatten())].reshape(old_shapes[2])
weights_combined = np.delete(weights_combined,np.s_[:len(weights1[2].numpy().flatten())])
len(weights_combined)

5

In [204]:
new_weights4 = weights_combined[:len(weights1[3].numpy().flatten())].reshape(old_shapes[3])
weights_combined = np.delete(weights_combined,np.s_[:len(weights1[3].numpy().flatten())])
len(weights_combined)

0

In [186]:
weights_combined = np.delete(weights_combined,np.s_[:len(weights1[3].numpy().flatten())])

In [205]:
w_list = [new_weights1, new_weights2, new_weights3, new_weights4]
w_list

[array([[-0.20550191,  1.        , -0.1247063 ,  0.36417955, -0.05435193,
          0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671],
        [-0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
          0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ],
        [-0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
         -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734],
        [ 0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
         -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ],
        [ 0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
         -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106],
        [ 0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
          0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ]],
       dtype=float32),
 array([ 0.0667546 , -0.03175627, -0.01404304,  0.04249647,  0.05407047,
         

In [206]:
model.set_weights(w_list)

In [207]:
model.weights

[<tf.Variable 'dense_10/kernel:0' shape=(6, 10) dtype=float32, numpy=
 array([[-0.20550191,  1.        , -0.1247063 ,  0.36417955, -0.05435193,
          0.16041505, -0.08009219, -0.4876371 ,  0.5270789 , -0.22714671],
        [-0.13508916,  0.16230476, -0.5823142 ,  0.59421295, -0.16791484,
          0.05303282, -0.43032938,  0.437056  , -0.29983795, -0.2542137 ],
        [-0.13452968,  0.2499662 , -0.09991783,  0.5022195 ,  0.0409832 ,
         -0.16415268,  0.09688812, -0.41114238,  0.13460892, -0.36726734],
        [ 0.35598248, -0.15569499,  0.25118637,  0.38806838, -0.6026911 ,
         -0.28360236,  0.33014894,  0.53754014, -0.5600314 , -0.5714094 ],
        [ 0.22438145,  0.12202936, -0.44010824, -0.22674373,  0.05882555,
         -0.56905484, -0.4846149 ,  0.40899366, -0.1061694 ,  0.46852106],
        [ 0.4313913 , -0.4670628 , -0.25587487,  0.08854097,  0.26260144,
          0.15318161, -0.47664177, -0.52249   , -0.21726507, -0.4849761 ]],
       dtype=float32)>,
 <tf.Variab

In [118]:
model.layers[0].set_weights([new_weights1,weights1[1].numpy()])

In [5]:
from math import sin
sin(65)

0.8268286794901034

In [6]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#Hands on machine learning book page 293
import tensorflow as tf
from tensorflow import keras
print(tf.__version__, keras.__version__)


In [ ]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()


In [ ]:
print(X_train_full.shape, X_train_full.dtype)

In [ ]:
X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [ ]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
 "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]


In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[6,1]))
model.add(keras.layers.Dense(10, activation="relu"))
model.add(keras.layers.Dense(6, activation="softmax"))


In [ ]:
model.summary()

In [ ]:
model.compile(loss="sparse_categorical_crossentropy",
 optimizer="sgd",
 metrics=["accuracy"])


In [ ]:
history = model.fit(X_train, y_train, epochs=30,validation_data=(X_valid, y_valid))

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1) # set the vertical range to [0-1]
plt.show()


In [ ]:
history.history["accuracy"
]

In [6]:
my_dict = {0: 5.0, 1: 1.0, 2: 10.31865}
sorted(my_dict, key=my_dict.get, reverse=True)[:2]

[2, 0]