In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy


In [2]:
physical_devices = tf.config.experimental.list_physical_devices("GPU")
print(len(physical_devices))

0


In [2]:
model = Sequential([
        Dense(units=10, input_shape=(6,), activation="relu", bias_initializer="RandomNormal" ), #first hidden layer
        Dense(units=5, activation="softmax", bias_initializer="RandomNormal") #output
        ])

In [17]:
troll_list = np.array([1,2,3,4,5,6])
troll_list = troll_list.reshape(1,6)
troll_list

array([[1, 2, 3, 4, 5, 6]])

In [19]:
import numpy as np
prediction = model.predict(troll_list)

In [23]:
prediction.argmax()

4

In [24]:
prediction

array([[0.1003224 , 0.13282391, 0.01408724, 0.06381109, 0.6889554 ]],
      dtype=float32)

In [29]:
model.weights[1]

<tf.Variable 'dense_10/bias:0' shape=(10,) dtype=float32, numpy=
array([ 0.07141653,  0.02657398,  0.00952234,  0.04220833,  0.05110628,
        0.07044599,  0.01900799,  0.02041466, -0.05675307,  0.10267283],
      dtype=float32)>

In [ ]:
list1 = [0,-2,5,1]
list1.sort()

In [ ]:
#Hands on machine learning book page 293
import tensorflow as tf
from tensorflow import keras
print(tf.__version__, keras.__version__)


In [ ]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()


In [ ]:
print(X_train_full.shape, X_train_full.dtype)

In [ ]:
X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [ ]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
 "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]


In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[6,1]))
model.add(keras.layers.Dense(10, activation="relu"))
model.add(keras.layers.Dense(6, activation="softmax"))


In [ ]:
model.summary()

In [ ]:
model.compile(loss="sparse_categorical_crossentropy",
 optimizer="sgd",
 metrics=["accuracy"])


In [ ]:
history = model.fit(X_train, y_train, epochs=30,validation_data=(X_valid, y_valid))

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1) # set the vertical range to [0-1]
plt.show()


In [ ]:
history.history["accuracy"
]